server:
  port: 8888

spring:
  application:
    name: mszlu-blog
  redis:
    host: localhost
    port: 6379

  #    数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mszl?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: '#2018iGwin'
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus
mybatis-plus:
  configuration:
#    日志标准输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      表名前缀
      table-prefix: ms_
