server:
  port: 8888

spring:
  application:
    name: mszlu-blog
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-request-size: 20MB # 上传文件总最大值
      max-file-size: 2MB # 单个文件最大值
  datasource:
    url: jdbc:mysql://localhost:3306/mszl?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: '#2018iGwin'
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志标准输出
  global-config:
    db-config:
      table-prefix: ms_ # 表名前缀
